# Generated by Django 4.2.15 on 2025-07-01 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=56)),
                ('dsc', models.TextField(max_length=215)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('dsc', models.TextField(max_length=315)),
                ('text', models.TextField(max_length=4500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.postcategory')),
            ],
        ),
    ]
