# Generated by Django 4.2.15 on 2025-08-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='is_subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
